// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Y2DL.Minimal.Database;

#nullable disable

namespace Y2DL.Minimal.Migrations
{
    [DbContext(typeof(Y2dlDbContext))]
    [Migration("20240115003159_Y2DL.Minimal.Initial")]
    partial class Y2DLMinimalInitial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.26");

            modelBuilder.Entity("Y2DL.Minimal.Database.ChannelReleasesLatestVideo", b =>
                {
                    b.Property<string>("VideoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChannelId")
                        .HasColumnType("TEXT");

                    b.HasKey("VideoId");

                    b.ToTable("ChannelReleasesLatestVideos");
                });

            modelBuilder.Entity("Y2DL.Minimal.Database.DynamicChannelInfoMessages", b =>
                {
                    b.Property<string>("Hash")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("MessageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("YoutubeChannelId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Hash");

                    b.ToTable("DynamicChannelInfoMessages");
                });
#pragma warning restore 612, 618
        }
    }
}
